### ISSUE TITLE
Update README.md to be Consistent with other Projects.

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-botframework-export#1]
_Overview:_ Just going through this to have it, as we release this to more users.

**Comment by NikV** [comment]
Reminder: It needs to have the video before this issue is closed.

**Comment by obaid** [comment]
Can we use the video that @nonnontrivial created earlier?

**Comment by NikV** [comment]
@obaid Working on overdubbing it as we speak! I had an idea to slightly improve it.
