### ISSUE TITLE
Response Variations in generated .lg file

### ISSUE THREAD

**Issue by manish-95** [Botmock/botmock-botframework-export#21]
**Is your feature request related to a problem? Please describe.**
When I use the export script to generate the .lg output file containing responses for a BotMock project, I get only the main response, and not the response variations.

**Describe the solution you'd like**
The generated .lg file should contain not only the main response text, but also the response variations.

**Comment by Gauhar** [comment]
Hi @manish-95 - Thank you for reaching out. I am Gauhar from Botmock. I am going to triage this issue for out integrations team and we will have an update for you after New years. Thank you and Happy New Year. :)

Cheers
